CREATE DATABASE IF NOT EXISTS Biblioteca 
DEFAULT CHARACTER SET utf8 
DEFAULT COLLATE utf8_general_ci;

USE Biblioteca;

DROP TABLE IF EXISTS Prestamo;
DROP TABLE IF EXISTS Libro;
DROP TABLE IF EXISTS Socio;
DROP TABLE IF EXISTS Tema;
DROP TABLE IF EXISTS Editorial;
DROP TABLE IF EXISTS Autor;
DROP TABLE IF EXISTS Actualizaciones_Libro;

CREATE TABLE Autor (
	idAutor INT NOT NULL AUTO_INCREMENT,
	NombreAutor VARCHAR(60) NOT NULL,
	PRIMARY KEY (idAutor)
) ENGINE=InnoDB;

CREATE TABLE Editorial (
	idEditorial INT NOT NULL AUTO_INCREMENT,
	NombreEditorial VARCHAR(30) NOT NULL,
	Direccion VARCHAR (100) NOT NULL,
	Telefono VARCHAR (15) NOT NULL, 
 	PRIMARY KEY (idEditorial)
) ENGINE=InnoDB;

CREATE TABLE Tema (
	idTema INT NOT NULL AUTO_INCREMENT,
	NombreTema VARCHAR(30) NOT NULL,
	PRIMARY KEY (idTema)
) ENGINE=InnoDB;

CREATE TABLE Socio (
	idSocio INT NOT NULL AUTO_INCREMENT,
	NombreCompleto VARCHAR(60) NOT NULL,
	Direccion VARCHAR(100) NOT NULL,
	Correo VARCHAR(25) NULL DEFAULT 'Sin Correo',
	Telefono VARCHAR(15) NOT NULL,
	Foto VARCHAR(20) NOT NULL,
	PRIMARY KEY (idSocio)
) ENGINE=InnoDB;

CREATE TABLE Libro (
	idLibro INT NOT NULL AUTO_INCREMENT,
	ISBN VARCHAR(20) NOT NULL UNIQUE,
	Titulo VARCHAR(65) NOT NULL,
	NumeroEjemplares TINYINT NOT NULL,
	idAutor INT NOT NULL,
	idEditorial INT NOT NULL,
	idTema INT NOT NULL,
	PRIMARY KEY (idLibro),
	FOREIGN KEY (idAutor) REFERENCES Autor (idAutor) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (idEditorial) REFERENCES Editorial (idEditorial) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (idTema) REFERENCES Tema (idTema) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE Prestamo (
	idPrestamo INT NOT NULL AUTO_INCREMENT,
	FechaPrestamo DATE NOT NULL,
	FechaEntrega DATE NOT NULL,
	idSocio INT NOT NULL,
	idLibro INT NOT NULL,
	PRIMARY KEY (idPrestamo),
	FOREIGN KEY (idSocio) REFERENCES Socio (idSocio) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (idLibro) REFERENCES Libro (idLibro) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE Actualizaciones_Libro (
	ISBNAnterior VARCHAR(20) NOT NULL,
	TituloAnterior VARCHAR(65) NOT NULL,
	NumeroEjemplaresAnterior TINYINT NOT NULL,
	ISBNNuevo VARCHAR(20) NOT NULL,
	TituloNuevo VARCHAR(65) NOT NULL,
	NumeroEjemplaresNuevo TINYINT NOT NULL,
	Usuario VARCHAR(15) NOT NULL,
	FechaModificacion DATETIME NOT NULL
) ENGINE=MyISAM;